# Generated by Django 4.2.3 on 2023-08-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.publication'),
        ),
    ]
